[build]
  command = "yarn build"
  functions = "lambda"
  publish="build"

[dev]
  command = "yarn serve"
  port = 3000
  publish = "build"
  functionsPort = 9000

[production]
  command = "yarn build"
  functions = "lambda"
  publish = "build"

[[redirects]]
  from = "https://skydark.netlify.app/*"
  to = "https://skydark.app/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://dark-sky.netlify.app/*"
  to = "https://skydark.app/:splat"
  status = 301
  force = true

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Content-Security-Policy = "form-action https:"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Strict-Transport-Security = "max-age=2592000"
    Feature-Policy = "geolocation 'self'; midi 'none'; ; sync-xhr 'self'; microphone 'none'; camera 'none'; magnetometer 'none'; gyroscope 'self'; fullscreen 'self'; payment 'none'"
